version = 0.1

[dev.deploy.parameters]
stack_name = "feed-films-dev"
s3_bucket = "aws-sam-cli-managed-default-samclisourcebucket-7lno1r3muddd"
s3_prefix = "feed-films-dev"
region = "eu-west-1"
confirm_changeset = true
capabilities = "CAPABILITY_IAM"
image_repositories = []
parameter_overrides = "Environment=dev"

[pre.deploy.parameters]
stack_name = "feed-films-pre"
s3_bucket = "aws-sam-cli-managed-default-samclisourcebucket-7lno1r3muddd"
s3_prefix = "feed-films-pre"
region = "eu-west-1"
confirm_changeset = true
capabilities = "CAPABILITY_IAM"
image_repositories = []
parameter_overrides = "Environment=pre"


[pro.deploy.parameters]
stack_name = "feed-films-pro"
s3_bucket = "aws-sam-cli-managed-default-samclisourcebucket-7lno1r3muddd"
s3_prefix = "feed-films-pro"
region = "eu-west-1"
confirm_changeset = true
capabilities = "CAPABILITY_IAM"
image_repositories = []
parameter_overrides = "Environment=pro"